-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
-- Remote Path: game:GetService("ReplicatedStorage").Remotes.NewGame
 
local A_1 = "Shadow"
local A_2 = "Female"
local A_3 = "http://www.roblox.com/asset/?id=385872238"
local A_4 = "Blue"
local A_5 = "http://www.roblox.com/asset/?id=318843897"
local A_6 = "Blue"
local A_7 = "http://www.roblox.com/asset/?id=1539658809"
local A_8 = "Pastel brown"
local A_9 = "http://www.roblox.com/asset/?id=167554431 "
local A_10 = 
{
	[1] = 0.88627457618713, 
	[2] = 0.60784316062927, 
	[3] = 0.25098040699959
}
local A_11 = 0
local A_12 = 
{
	[1] = 1, 
	[2] = 1, 
	[3] = 1
}
game:GetService("ReplicatedStorage").Remotes.NewGame:FireServer(A_1, A_2, A_3, A_4, A_5, A_6, A_7, A_8, A_9, A_10, A_11, A_12)