-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
-- Remote Path: game:GetService("Players").MangoNyah.Backpack.VoidGaster.VoidStrike.Rise
 
local A_1 = Vector3.new(110.659096, 0, -1.35289574)
local Event = game.Players.MangoNyah.Backpack.VoidGaster.VoidStrike.Rise
Event:FireServer(A_1, "no")
