local player = game.Players.LocalPlayer
player.Character.HumanoidRootPart.CFrame = CFrame.new(0, 0, 0)

wait()

local plat = Instance.new("Part", workspace)
plat.Anchored = true
plat.CFrame = player.Character.HumanoidRootPart.CFrame + Vector3.new(0, -15, 0)
plat.Size = Vector3.new(25, 2, 25)

while wait() do
    for i,v in pairs(game.Players:GetPlayers()) do
        if v ~= player and pcall(function() a=v.Character.HumanoidRootPart;b=v.Character.Humanoid;end) and v.Character.Humanoid.Health > 0 and not v.Character:FindFirstChild("ForceField") then
            repeat
                pcall(function()
                    v.Character.HumanoidRootPart.CFrame = player.Character.HumanoidRootPart.CFrame * CFrame.new(0, 0, -5)
                end)
                wait()
                Input.LeftClick()
            until not pcall(function() return v.Character.HumanoidRootPart, v.Character.Humanoid end) or v.Character.Humanoid.Health <= 0 or v.Character:FindFirstChild("ForceField")
        end
    end
end

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "SmokeGrenade"
local A_2 = CFrame.new(28.0700836, 64.2376938, 414.027069, -0.947001338, -0.0243510734, 0.320305407, 0, 0.997122705, 0.0758057907, -0.321229726, 0.0717881843, -0.944276452)
local Event = game:GetService("ReplicatedStorage").Aero.AeroRemoteServices.ReplicationService.ThrowGrenade
Event:InvokeServer(A_1, A_2)
